### ISSUE TITLE
change function errors but still still updates the record

### ISSUE THREAD

**Issue by keeganstothert** [surrealdb/surrealdb.js#74]
I get `PermissionError: Unable to update record: product:byqu8riqoe8bxfqca5xe` when running

`const updated = await db.change(id, product);`

**Comment by BridgerB** [comment]
I am having this same issue with `db. change` and `db.update` using javascript or deno with version `1.0.0_beta.9-1`

**Comment by kearfy** [comment]
Fixed this today! Thanks :)

**Comment by tw1t611** [comment]
@kearfy This error isn't solved for me in 0.6.0.
It works when using an integer as index, but doesn't work if a string was used.

works
```js
  let db_product = await db.change(
    "products:1",
    product
  );
```

throws error:
```js
  let db_product = await db.change(
    "products:gold-bond-healing-skin-therapy-lotion-with-aloe-20-oz-non-greasy-and-hypoallergenic",
    product
  );
```

error message
```bash
file:///home/user/Projects/bestproductinsight-com/scripts/node_modules/.pnpm/surrealdb.js@0.6.0/node_modules/surrealdb.js/esm/index.js:414
    throw new error(errormessage);
          ^

PermissionError: Unable to update record: products:gold-bond-healing-skin-therapy-lotion-with-aloe-20-oz-non-greasy-and-hypoallergenic
    at Surreal._Surreal_outputHandler (file:///home/user/Projects/bestproductinsight-com/scripts/node_modules/.pnpm/surrealdb.js@0.6.0/node_modules/surrealdb.js/esm/index.js:414:11)
    at Surreal.change (file:///home/user/Projects/bestproductinsight-com/scripts/node_modules/.pnpm/surrealdb.js@0.6.0/node_modules/surrealdb.js/esm/index.js:360:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///home/user/Projects/bestproductinsight-com/scripts/generate-content/write-to-db.js:17:20)
    at async main (file:///home/user/Projects/bestproductinsight-com/scripts/generate-content/main.js:21:5)

Node.js v18.12.1
```

I am using a schemafull setup
```sql
  BEGIN TRANSACTION;

  REMOVE table categories;
  REMOVE table products;

  DEFINE TABLE categories SCHEMAFULL;
  DEFINE FIELD name ON categories TYPE string;
  DEFINE FIELD products.* ON categories TYPE record(products);

  DEFINE TABLE products SCHEMAFULL;
  DEFINE FIELD name ON products type string;
  DEFINE FIELD imageUrls ON products type array;
  DEFINE FIELD imageUrls.* ON TABLE products TYPE string;
  DEFINE FIELD amazonUrl ON products type string;

  COMMIT TRANSACTION
```
